### ISSUE TITLE
App folders not working

### ISSUE THREAD

**Issue by derekstephen** [Exho1/gPhone#18]
Whenever I try to drag 2 apps to make a folder I get this lua error.

```
[ERROR] addons/gphonedarkrp/lua/gphone/cl_phone.lua:529: attempt to index a nil value
  1. Func - addons/gphonedarkrp/lua/gphone/cl_phone.lua:529
   2. CallReceiverFunction - lua/includes/extensions/client/panel/dragdrop.lua:184
    3. Drop - lua/includes/extensions/client/panel/dragdrop.lua:76
     4. DragMouseRelease - lua/includes/extensions/client/panel/dragdrop.lua:459
      5. OnMouseReleased - lua/vgui/dlabel.lua:173
       6. unknown - lua/vgui/dimagebutton.lua:129
```

I have tried updating the code on the server by deleting the files and uploading the most recent code off of github.

Any ideas?

**Comment by Exho1** [comment]
Download the latest version from github, I added a check to prevent that error from happening. Not entirely sure what causes though.

**Comment by derekstephen** [comment]
It works now. Thank you for the fast reply and fix.
