### ISSUE TITLE
Can't use the phone

### ISSUE THREAD

**Issue by Sachha** [Exho1/gPhone#19]
We can't use the phone since the latest update

With the Workshop version, it's still possible but not with the Github version :x 

That didn't make any error, but when we try to call someone in our contact that do nothing, and when we try to call someone with his number, that say that the owner is not avaible :x

**Comment by Exho1** [comment]
Well this is unfortunate

**Comment by Exho1** [comment]
Should've closed this a long time ago. Any of those issues should be fixed

**Comment by mark27205** [comment]
ok
