### ISSUE TITLE
Jobs/ Finances Error

### ISSUE THREAD

**Issue by rangerrory** [Exho1/gPhone#25]
If i attempt to get the Jobs or Finances app from the store, it throws up this error, any ideas?

[ERROR] lua/includes/extensions/table.lua:94: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. HasValue - lua/includes/extensions/table.lua:94
    3. DoClick - addons/gphone/lua/gphone/apps/store.lua:140
     4. unknown - lua/vgui/dlabel.lua:232

**Comment by Exho1** [comment]
Fixed
