### ISSUE TITLE
Phone doesn't generate number

### ISSUE THREAD

**Issue by Dunkstormen** [Exho1/gPhone#7]
It says that it is generating a number for me, but when i look in the contacts it says ERRO-RNUM

**Comment by Exho1** [comment]
Um, any more information so I can actually do something about it?

**Comment by Dunkstormen** [comment]
[gPhone]: Created seen tutorial file
[gPhone]: Importing applications...
[gPhone]: 80 220 80 255, !#4, meta )Generating number for Nido Johnson
[gPhone]: 80 220 80 255, !#4, meta )Generating number for Nido Johnson
[gPhone]: 80 220 80 255, !#4, meta )Generating number for Nido Johnson
[gPhone]: 80 220 80 255, !#4, meta )Generating number for Nido Johnson
[gPhone]: 80 220 80 255, !#4, meta )Generating number for Nido Johnson
[gPhone]: 80 220 80 255, !#4, meta )Generating number for Nido Johnson
[gPhone]: Nido Johnson has an invalid phone number! A new one will be generated
[gPhone]: Nido Johnson has an invalid phone number! A new one will be generated
[gPhone]: 80 220 80 255, !#4, meta )Generating number for Benjamin Joergensen
[gPhone]: 80 220 80 255, !#4, meta )Generating number for Benjamin Joergensen
[gPhone]: 80 220 80 255, !#4, meta )Generating number for Nido Johnson
[gPhone]: 80 220 80 255, !#4, meta )Generating number for Nido Johnson
[gPhone]: 80 220 80 255, !#4, meta )Generating number for Nido Johnson
[gPhone]: 80 220 80 255, !#4, meta )Generating number for Nido Johnson
[gPhone]: 80 220 80 255, !#4, meta )Generating number for Nido Johnson
[gPhone]: 80 220 80 255, !#4, meta )Generating number for Nido Johnson

**Comment by Dunkstormen** [comment]
Thats all it says.

**Comment by Exho1** [comment]
Yeah I found the issue.. I added a '<=' that should've just been a '<'

**Comment by Dunkstormen** [comment]
Can you tell me where so i just can edit it?
:P

**Comment by Exho1** [comment]
Line 386 of sh_util.lua but I just pushed a commit to Github to fix it.
