### ISSUE TITLE
Open/close bind not working at all

### ISSUE THREAD

**Issue by AmyJeanes** [Exho1/gPhone#8]
No errors in console or anything, but the bind just doesn't work at all. I've had to manually call `gPhone.showPhone()` to get it to open. I've tried changing to different keys in the settings app and it does absolutely nothing. Running latest workshop version of course.

**Comment by Exho1** [comment]
Are you holding the key or pressing it?

**Comment by AmyJeanes** [comment]
Holding it, for (above) the 0.75 seconds as default. For the record, pressing didn't work either.

**Comment by Exho1** [comment]
Found the issue, fixed

**Comment by AmyJeanes** [comment]
Works now, thanks.
