### ISSUE TITLE
gPhone can activate while typing in chatbox/console

### ISSUE THREAD

**Issue by AmyJeanes** [Exho1/gPhone#9]
If you hold the key down for the time while typing in the chat-box it will activate. This is mainly a problem for people who use very low key hold times, such as 0.

**Comment by Exho1** [comment]
It happens in the console as well, I know

**Comment by Exho1** [comment]
Fixed

**Comment by AmyJeanes** [comment]
I'm curious, how did you fix this?

**Comment by Exho1** [comment]
I found two functions for checking if the console or main menu was open and then just set a boolean based on opening and closing the chat.

local canOpenPhone = true
hook.Add( "Think", "gPhone_openAndCloseKey", function()
    -- Prevents the phone from being opened while chatting, in console, or in the main menu
    if not canOpenPhone or gui.IsConsoleVisible() or gui.IsGameUIVisible() then return end

```
-- snip code
```

end)

hook.Add("StartChat", "gPhone_liveAndLetChat", function()
    canOpenPhone = false
end)

hook.Add("FinishChat", "gPhone_weDoneChatting", function()
    canOpenPhone = true
end)

**Comment by AmyJeanes** [comment]
Ah, nice. There should really be a function to see if chat is open, I hate doing it using the Start/FinishChat hooks

**Comment by Exho1** [comment]
Yeah that would be lovely
